/** @file gui_interface.c
 *	@brief Defines all the interfaces and hooks up all the signals for the
 *	GUI. This file was originally generated by glade.
 *
 *	@author Cornell Wright
 */

#include "config_defaults.h"
#include "gui_config.h"

#include <sys/types.h>
#include <sys/stat.h>
#ifdef HAVE_UNISTD_H
//#include <unistd.h>
#endif
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gui_callbacks.h"
#include "gui_interface.h"
#include "gui_support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *main_notebook;
#ifdef USE_MANUAL_MODE
  GtkWidget *vbox1;
  GtkWidget *label1;
  GtkWidget *table11;
  GtkWidget *inner_slide_actual_pos;
  GtkWidget *inner_slide_set_pos;
  GtkWidget *inner_slide_set_force;
  GtkWidget *label38;
  GtkWidget *label39;
  GtkWidget *label40;
  GtkWidget *inner_slide_actual_force;
  GtkWidget *hseparator6;
  GtkWidget *label2;
  GtkWidget *table6;
  GtkWidget *outer_slide_actual_pos;
  GtkWidget *outer_slide_set_force;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *outer_slide_actual_force;
  GtkWidget *outer_slide_set_pos;
  GtkWidget *hseparator7;
  GtkWidget *label3;
  GtkWidget *table7;
  GtkWidget *inner_actual_pos;
  GtkWidget *inner_set_pos;
  GtkWidget *inner_set_force;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *inner_actual_force;
  GtkWidget *hseparator8;
  GtkWidget *label4;
  GtkWidget *table8;
  GtkWidget *bot_actual_pos;
  GtkWidget *bot_set_pos;
  GtkWidget *bot_set_force;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *bot_actual_force;
  GtkWidget *hseparator9;
  GtkWidget *label5;
  GtkWidget *table9;
  GtkWidget *ul_actual_pos;
  GtkWidget *ul_set_pos;
  GtkWidget *ul_set_force;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *label30;
  GtkWidget *ul_actual_force;
  GtkWidget *hseparator10;
  GtkWidget *label6;
  GtkWidget *table10;
  GtkWidget *ur_actual_pos;
  GtkWidget *ur_set_pos;
  GtkWidget *ur_set_force;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label33;
  GtkWidget *label34;
  GtkWidget *ur_actual_force;
  GtkWidget *hseparator11;
  GtkWidget *hbox5;
  GtkWidget *apply_btn;
  GtkWidget *hbox3;
  GtkWidget *image2;
  GtkWidget *label36;
  GtkWidget *checkbutton1;
  GtkWidget *alignment3;
  GtkWidget *hbox6;
  GtkWidget *image3;
  GtkWidget *label41;
  GtkWidget *checkbutton2;
  GtkWidget *alignment4;
  GtkWidget *hbox10;
  GtkWidget *image5;
  GtkWidget *label71;
  GtkWidget *statusbar1;
  GtkWidget *label_manual_mode;
#endif /* USE_MANUAL_MODE */
  GtkWidget *vbox2;
  GtkWidget *table12;
  GtkWidget *hseparator12;
  GtkWidget *label37;
  GtkWidget *label44;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *inner_slide_actual_pos_guided;
  GtkWidget *inner_slide_actual_force_guided;
  GtkWidget *table14;
  GtkWidget *hseparator14;
  GtkWidget *label50;
  GtkWidget *label51;
  GtkWidget *label52;
  GtkWidget *outer_slide_actual_pos_guided;
  GtkWidget *outer_slide_actual_force_guided;
  GtkWidget *table15;
  GtkWidget *hseparator15;
  GtkWidget *label53;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *inner_actual_pos_guided;
  GtkWidget *inner_actual_force_guided;
  GtkWidget *table16;
  GtkWidget *hseparator16;
  GtkWidget *label56;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *bot_actual_pos_guided;
  GtkWidget *bot_actual_force_guided;
  GtkWidget *table17;
  GtkWidget *hseparator17;
  GtkWidget *label59;
  GtkWidget *label60;
  GtkWidget *label61;
  GtkWidget *ul_actual_pos_guided;
  GtkWidget *ul_actual_force_guided;
  GtkWidget *table18;
  GtkWidget *hseparator18;
  GtkWidget *label62;
  GtkWidget *label63;
  GtkWidget *label64;
  GtkWidget *ur_actual_pos_guided;
  GtkWidget *ur_actual_force_guided;
  GtkWidget *hbox7;
  GtkWidget *hbox8;
  GtkWidget *vbox3;
  GtkWidget *vbox4;
  GtkWidget *label70;
  GtkWidget *hbox9;
  GtkWidget *hscale20;
  GtkWidget *vscale1;
  GtkWidget *table19;
  GtkWidget *label68;
  GtkWidget *label69;
  GtkWidget *next_mode_label;
  GtkWidget *next_mode;
  GtkWidget *label65;
  GtkWidget *label66;
  GtkWidget *run_pause;
  GtkWidget *pause_label;
  GtkWidget *vbox5;
  GtkWidget *hbox11;
  GtkWidget *image6;
  GtkWidget *image7;
  GtkWidget *scrolledwindow1;
  GtkWidget *textview1;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (main_window, 550, -1);
  gtk_window_set_title (GTK_WINDOW (main_window), _("CardioARM"));
  gtk_window_set_icon_name (GTK_WINDOW (main_window), "gtk-about");

  main_notebook = gtk_notebook_new ();
  gtk_widget_show (main_notebook);
  gtk_container_add (GTK_CONTAINER (main_window), main_notebook);

#ifdef USE_MANUAL_MODE

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_notebook), vbox1);

  label1 = gtk_label_new (_("Inner Slide"));
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox1), label1, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label1), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label1), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label1), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label1), TRUE);

  table11 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table11);
  gtk_box_pack_start (GTK_BOX (vbox1), table11, TRUE, TRUE, 0);

  inner_slide_actual_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (inner_slide_actual_pos);
  gtk_table_attach (GTK_TABLE (table11), inner_slide_actual_pos, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (inner_slide_actual_pos, FALSE);
  gtk_scale_set_digits (GTK_SCALE (inner_slide_actual_pos), 2);

  inner_slide_set_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (inner_slide_set_pos);
  gtk_table_attach (GTK_TABLE (table11), inner_slide_set_pos, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (inner_slide_set_pos), 2);

  inner_slide_set_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[INNER_SLIDE] * motor_limit_current_fractions_const[INNER_SLIDE], 0.1, 1, 0)));
  gtk_widget_show (inner_slide_set_force);
  gtk_table_attach (GTK_TABLE (table11), inner_slide_set_force, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (inner_slide_set_force), 2);

  label37 = gtk_label_new (_("Set Postion (mm)"));
  gtk_widget_show (label37);
  gtk_table_attach (GTK_TABLE (table11), label37, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label37), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label37), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label37), TRUE);

  label38 = gtk_label_new (_("Set Force (ADC Ticks)"));
  gtk_widget_show (label38);
  gtk_table_attach (GTK_TABLE (table11), label38, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label38), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label38), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label38), TRUE);

  label39 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label39);
  gtk_table_attach (GTK_TABLE (table11), label39, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label39), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label39), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label39), TRUE);

  label40 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label40);
  gtk_table_attach (GTK_TABLE (table11), label40, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label40), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label40), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label40), TRUE);

  inner_slide_actual_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[INNER_SLIDE] * motor_limit_current_fractions_const[INNER_SLIDE], 0.1, 1, 0)));
  gtk_widget_show (inner_slide_actual_force);
  gtk_table_attach (GTK_TABLE (table11), inner_slide_actual_force, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (inner_slide_actual_force, FALSE);
  gtk_scale_set_digits (GTK_SCALE (inner_slide_actual_force), 2);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator6, TRUE, TRUE, 0);

  label2 = gtk_label_new (_("Outer Slide"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox1), label2, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label2), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label2), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label2), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label2), TRUE);

  table6 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table6);
  gtk_box_pack_start (GTK_BOX (vbox1), table6, TRUE, TRUE, 0);

  outer_slide_actual_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (outer_slide_actual_pos);
  gtk_table_attach (GTK_TABLE (table6), outer_slide_actual_pos, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (outer_slide_actual_pos, FALSE);
  gtk_scale_set_digits (GTK_SCALE (outer_slide_actual_pos), 2);

  outer_slide_set_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[OUTER_SLIDE] * motor_limit_current_fractions_const[OUTER_SLIDE], 0.1, 1, 0)));
  gtk_widget_show (outer_slide_set_force);
  gtk_table_attach (GTK_TABLE (table6), outer_slide_set_force, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (outer_slide_set_force), 2);

  label15 = gtk_label_new (_("Set Postion (mm)"));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table6), label15, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label15), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label15), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label15), TRUE);

  label16 = gtk_label_new (_("Set Force (ADC Ticks)"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table6), label16, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label16), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label16), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label16), TRUE);

  label17 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table6), label17, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label17), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label17), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label17), TRUE);

  label18 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table6), label18, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label18), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label18), TRUE);

  outer_slide_actual_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[OUTER_SLIDE] * motor_limit_current_fractions_const[OUTER_SLIDE], 0.1, 1, 0)));
  gtk_widget_show (outer_slide_actual_force);
  gtk_table_attach (GTK_TABLE (table6), outer_slide_actual_force, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (outer_slide_actual_force, FALSE);
  gtk_scale_set_digits (GTK_SCALE (outer_slide_actual_force), 2);

  outer_slide_set_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (outer_slide_set_pos);
  gtk_table_attach (GTK_TABLE (table6), outer_slide_set_pos, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (outer_slide_set_pos), 2);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_show (hseparator7);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator7, TRUE, TRUE, 0);

  label3 = gtk_label_new (_("Inner Tensioner"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vbox1), label3, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label3), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label3), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label3), TRUE);

  table7 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table7);
  gtk_box_pack_start (GTK_BOX (vbox1), table7, TRUE, TRUE, 0);

  inner_actual_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (inner_actual_pos);
  gtk_table_attach (GTK_TABLE (table7), inner_actual_pos, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (inner_actual_pos, FALSE);
  gtk_scale_set_digits (GTK_SCALE (inner_actual_pos), 2);

  inner_set_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (inner_set_pos);
  gtk_table_attach (GTK_TABLE (table7), inner_set_pos, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (inner_set_pos), 2);

  inner_set_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[INNER_TENSIONER] * motor_limit_current_fractions_const[INNER_TENSIONER], 0.1, 1, 0)));
  gtk_widget_show (inner_set_force);
  gtk_table_attach (GTK_TABLE (table7), inner_set_force, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (inner_set_force), 2);

  label19 = gtk_label_new (_("Set Postion (mm)"));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table7), label19, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label19), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label19), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label19), TRUE);

  label20 = gtk_label_new (_("Set Force (ADC Ticks)"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table7), label20, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label20), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label20), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label20), TRUE);

  label21 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table7), label21, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label21), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label21), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label21), TRUE);

  label22 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table7), label22, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label22), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label22), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label22), TRUE);

  inner_actual_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[INNER_TENSIONER] * motor_limit_current_fractions_const[INNER_TENSIONER], 0.1, 1, 0)));
  gtk_widget_show (inner_actual_force);
  gtk_table_attach (GTK_TABLE (table7), inner_actual_force, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (inner_actual_force, FALSE);
  gtk_scale_set_digits (GTK_SCALE (inner_actual_force), 2);

  hseparator8 = gtk_hseparator_new ();
  gtk_widget_show (hseparator8);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator8, TRUE, TRUE, 0);

  label4 = gtk_label_new (_("Bottom Tensioner"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (vbox1), label4, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label4), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label4), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label4), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label4), TRUE);

  table8 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table8);
  gtk_box_pack_start (GTK_BOX (vbox1), table8, TRUE, TRUE, 0);

  bot_actual_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (bot_actual_pos);
  gtk_table_attach (GTK_TABLE (table8), bot_actual_pos, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (bot_actual_pos, FALSE);
  gtk_scale_set_digits (GTK_SCALE (bot_actual_pos), 2);

  bot_set_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (bot_set_pos);
  gtk_table_attach (GTK_TABLE (table8), bot_set_pos, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (bot_set_pos), 2);

  bot_set_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[BOT_TENSIONER] * motor_limit_current_fractions_const[BOT_TENSIONER], 0.1, 1, 0)));
  gtk_widget_show (bot_set_force);
  gtk_table_attach (GTK_TABLE (table8), bot_set_force, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (bot_set_force), 2);

  label23 = gtk_label_new (_("Set Postion (mm)"));
  gtk_widget_show (label23);
  gtk_table_attach (GTK_TABLE (table8), label23, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label23), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label23), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label23), TRUE);

  label24 = gtk_label_new (_("Set Force (ADC Ticks)"));
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table8), label24, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label24), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label24), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table8), label25, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label25), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label25), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label25), TRUE);

  label26 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table8), label26, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label26), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label26), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label26), TRUE);

  bot_actual_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[BOT_TENSIONER] * motor_limit_current_fractions_const[BOT_TENSIONER], 0.1, 1, 0)));
  gtk_widget_show (bot_actual_force);
  gtk_table_attach (GTK_TABLE (table8), bot_actual_force, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (bot_actual_force, FALSE);
  gtk_scale_set_digits (GTK_SCALE (bot_actual_force), 2);

  hseparator9 = gtk_hseparator_new ();
  gtk_widget_show (hseparator9);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator9, TRUE, TRUE, 0);

  label5 = gtk_label_new (_("Upper Left Tensioner"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (vbox1), label5, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label5), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label5), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label5), TRUE);

  table9 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table9);
  gtk_box_pack_start (GTK_BOX (vbox1), table9, TRUE, TRUE, 0);

  ul_actual_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (ul_actual_pos);
  gtk_table_attach (GTK_TABLE (table9), ul_actual_pos, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (ul_actual_pos, FALSE);
  gtk_scale_set_digits (GTK_SCALE (ul_actual_pos), 2);

  ul_set_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (ul_set_pos);
  gtk_table_attach (GTK_TABLE (table9), ul_set_pos, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (ul_set_pos), 2);

  ul_set_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[UL_TENSIONER] * motor_limit_current_fractions_const[UL_TENSIONER], 0.1, 1, 0)));
  gtk_widget_show (ul_set_force);
  gtk_table_attach (GTK_TABLE (table9), ul_set_force, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (ul_set_force), 2);

  label27 = gtk_label_new (_("Set Postion (mm)"));
  gtk_widget_show (label27);
  gtk_table_attach (GTK_TABLE (table9), label27, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label27), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label27), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label27), TRUE);

  label28 = gtk_label_new (_("Set Force (ADC Ticks)"));
  gtk_widget_show (label28);
  gtk_table_attach (GTK_TABLE (table9), label28, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label28), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label28), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label28), TRUE);

  label29 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label29);
  gtk_table_attach (GTK_TABLE (table9), label29, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label29), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label29), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label29), TRUE);

  label30 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label30);
  gtk_table_attach (GTK_TABLE (table9), label30, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label30), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label30), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label30), TRUE);

  ul_actual_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[UL_TENSIONER] * motor_limit_current_fractions_const[UL_TENSIONER], 0.1, 1, 0)));
  gtk_widget_show (ul_actual_force);
  gtk_table_attach (GTK_TABLE (table9), ul_actual_force, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (ul_actual_force, FALSE);
  gtk_scale_set_digits (GTK_SCALE (ul_actual_force), 2);

  hseparator10 = gtk_hseparator_new ();
  gtk_widget_show (hseparator10);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator10, TRUE, TRUE, 0);

  label6 = gtk_label_new (_("Upper Right Tensioner"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (vbox1), label6, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label6), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label6), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label6), TRUE);

  table10 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table10);
  gtk_box_pack_start (GTK_BOX (vbox1), table10, TRUE, TRUE, 0);

  ur_actual_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (ur_actual_pos);
  gtk_table_attach (GTK_TABLE (table10), ur_actual_pos, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (ur_actual_pos, FALSE);
  gtk_scale_set_digits (GTK_SCALE (ur_actual_pos), 2);

  ur_set_pos = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (ur_set_pos);
  gtk_table_attach (GTK_TABLE (table10), ur_set_pos, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (ur_set_pos), 2);

  ur_set_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[UR_TENSIONER] * motor_limit_current_fractions_const[UR_TENSIONER], 0.1, 1, 0)));
  gtk_widget_show (ur_set_force);
  gtk_table_attach (GTK_TABLE (table10), ur_set_force, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_scale_set_digits (GTK_SCALE (ur_set_force), 2);

  label31 = gtk_label_new (_("Set Postion (mm)"));
  gtk_widget_show (label31);
  gtk_table_attach (GTK_TABLE (table10), label31, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label31), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label31), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label31), TRUE);

  label32 = gtk_label_new (_("Set Force (ADC Ticks)"));
  gtk_widget_show (label32);
  gtk_table_attach (GTK_TABLE (table10), label32, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label32), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label32), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label32), TRUE);

  label33 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label33);
  gtk_table_attach (GTK_TABLE (table10), label33, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label33), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label33), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label33), TRUE);

  label34 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label34);
  gtk_table_attach (GTK_TABLE (table10), label34, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label34), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label34), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label34), TRUE);

  ur_actual_force = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 200, 0.1, 1, 0)));
  gtk_widget_show (ur_actual_force);
  gtk_table_attach (GTK_TABLE (table10), ur_actual_force, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (ur_actual_force, FALSE);
  gtk_scale_set_digits (GTK_SCALE (ur_actual_force), 2);

  hseparator11 = gtk_hseparator_new ();
  gtk_widget_show (hseparator11);
  gtk_box_pack_start (GTK_BOX (vbox1), hseparator11, TRUE, TRUE, 0);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox5, TRUE, TRUE, 0);

  apply_btn = gtk_button_new ();
  gtk_widget_show (apply_btn);
  gtk_box_pack_end (GTK_BOX (hbox5), apply_btn, TRUE, FALSE, 0);
  gtk_widget_set_size_request (apply_btn, 73, -1);
  GTK_WIDGET_SET_FLAGS (apply_btn, GTK_CAN_DEFAULT);
  gtk_tooltips_set_tip (tooltips, apply_btn, _("Send changes on above sliders to probe."), NULL);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (apply_btn), hbox3);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox3), image2, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("Apply"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox3), label36, FALSE, FALSE, 0);

  checkbutton1 = gtk_check_button_new ();
  gtk_widget_show (checkbutton1);
  gtk_box_pack_start (GTK_BOX (hbox5), checkbutton1, FALSE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, checkbutton1, _("Causes changes to the sliders above to be immediately sent to the probe."), NULL);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (checkbutton1), alignment3);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox6);

  image3 = gtk_image_new_from_stock ("gtk-jump-to", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox6), image3, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("Auto Apply"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox6), label41, FALSE, FALSE, 0);
  gtk_label_set_single_line_mode (GTK_LABEL (label41), TRUE);

  checkbutton2 = gtk_check_button_new ();
  gtk_widget_show (checkbutton2);
  gtk_box_pack_start (GTK_BOX (hbox5), checkbutton2, FALSE, FALSE, 4);
  gtk_tooltips_set_tip (tooltips, checkbutton2, _("Switch between relative and absolute positioning mode."), NULL);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (checkbutton2), alignment4);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox10);

  image5 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox10), image5, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("Relative Positoning"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox10), label71, FALSE, FALSE, 0);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  label_manual_mode = gtk_label_new (_("Manual Mode"));
  gtk_widget_show (label_manual_mode);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 0), label_manual_mode);

#endif /* USE_MANUAL_MODE */

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (main_notebook), vbox2);

  table12 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table12);
  gtk_box_pack_start (GTK_BOX (vbox2), table12, TRUE, TRUE, 0);

  hseparator12 = gtk_hseparator_new ();
  gtk_widget_show (hseparator12);
  gtk_table_attach (GTK_TABLE (table12), hseparator12, 0, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label44 = gtk_label_new (_("Inner Slide"));
  gtk_widget_show (label44);
  gtk_table_attach (GTK_TABLE (table12), label44, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label44), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label44), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label44), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label44), TRUE);

  label45 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label45);
  gtk_table_attach (GTK_TABLE (table12), label45, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label45), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label45), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label45), TRUE);

  label46 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label46);
  gtk_table_attach (GTK_TABLE (table12), label46, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label46), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label46), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label46), TRUE);

  inner_slide_actual_pos_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (inner_slide_actual_pos_guided);
  gtk_table_attach (GTK_TABLE (table12), inner_slide_actual_pos_guided, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (inner_slide_actual_pos_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (inner_slide_actual_pos_guided), 2);

  inner_slide_actual_force_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[INNER_SLIDE] * motor_limit_current_fractions_const[INNER_SLIDE], 0.1, 1, 0)));
  gtk_widget_show (inner_slide_actual_force_guided);
  gtk_table_attach (GTK_TABLE (table12), inner_slide_actual_force_guided, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (inner_slide_actual_force_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (inner_slide_actual_force_guided), 2);

  table14 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table14);
  gtk_box_pack_start (GTK_BOX (vbox2), table14, TRUE, TRUE, 0);

  hseparator14 = gtk_hseparator_new ();
  gtk_widget_show (hseparator14);
  gtk_table_attach (GTK_TABLE (table14), hseparator14, 0, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label50 = gtk_label_new (_("Outer Slide"));
  gtk_widget_show (label50);
  gtk_table_attach (GTK_TABLE (table14), label50, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label50), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label50), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label50), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label50), TRUE);

  label51 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label51);
  gtk_table_attach (GTK_TABLE (table14), label51, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label51), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label51), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label51), TRUE);

  label52 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label52);
  gtk_table_attach (GTK_TABLE (table14), label52, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label52), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label52), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label52), TRUE);

  outer_slide_actual_pos_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (outer_slide_actual_pos_guided);
  gtk_table_attach (GTK_TABLE (table14), outer_slide_actual_pos_guided, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (outer_slide_actual_pos_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (outer_slide_actual_pos_guided), 2);

  outer_slide_actual_force_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[OUTER_SLIDE] * motor_limit_current_fractions_const[OUTER_SLIDE], 0.1, 1, 0)));
  gtk_widget_show (outer_slide_actual_force_guided);
  gtk_table_attach (GTK_TABLE (table14), outer_slide_actual_force_guided, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (outer_slide_actual_force_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (outer_slide_actual_force_guided), 2);

  table15 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table15);
  gtk_box_pack_start (GTK_BOX (vbox2), table15, TRUE, TRUE, 0);

  hseparator15 = gtk_hseparator_new ();
  gtk_widget_show (hseparator15);
  gtk_table_attach (GTK_TABLE (table15), hseparator15, 0, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label53 = gtk_label_new (_("Inner Tensioner"));
  gtk_widget_show (label53);
  gtk_table_attach (GTK_TABLE (table15), label53, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label53), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label53), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label53), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label53), TRUE);

  label54 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label54);
  gtk_table_attach (GTK_TABLE (table15), label54, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label54), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label54), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label54), TRUE);

  label55 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label55);
  gtk_table_attach (GTK_TABLE (table15), label55, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label55), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label55), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label55), TRUE);

  inner_actual_pos_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (inner_actual_pos_guided);
  gtk_table_attach (GTK_TABLE (table15), inner_actual_pos_guided, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (inner_actual_pos_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (inner_actual_pos_guided), 2);

  inner_actual_force_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[INNER_TENSIONER] * motor_limit_current_fractions_const[INNER_TENSIONER], 0.1, 1, 0)));
  gtk_widget_show (inner_actual_force_guided);
  gtk_table_attach (GTK_TABLE (table15), inner_actual_force_guided, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (inner_actual_force_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (inner_actual_force_guided), 2);

  table16 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table16);
  gtk_box_pack_start (GTK_BOX (vbox2), table16, TRUE, TRUE, 0);

  hseparator16 = gtk_hseparator_new ();
  gtk_widget_show (hseparator16);
  gtk_table_attach (GTK_TABLE (table16), hseparator16, 0, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label56 = gtk_label_new (_("Bottom Tensioner"));
  gtk_widget_show (label56);
  gtk_table_attach (GTK_TABLE (table16), label56, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label56), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label56), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label56), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label56), TRUE);

  label57 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label57);
  gtk_table_attach (GTK_TABLE (table16), label57, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label57), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label57), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label57), TRUE);

  label58 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label58);
  gtk_table_attach (GTK_TABLE (table16), label58, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label58), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label58), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label58), TRUE);

  bot_actual_pos_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (bot_actual_pos_guided);
  gtk_table_attach (GTK_TABLE (table16), bot_actual_pos_guided, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (bot_actual_pos_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (bot_actual_pos_guided), 2);

  bot_actual_force_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[BOT_TENSIONER] * motor_limit_current_fractions_const[BOT_TENSIONER], 0.1, 1, 0)));
  gtk_widget_show (bot_actual_force_guided);
  gtk_table_attach (GTK_TABLE (table16), bot_actual_force_guided, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (bot_actual_force_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (bot_actual_force_guided), 2);

  table17 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table17);
  gtk_box_pack_start (GTK_BOX (vbox2), table17, TRUE, TRUE, 0);

  hseparator17 = gtk_hseparator_new ();
  gtk_widget_show (hseparator17);
  gtk_table_attach (GTK_TABLE (table17), hseparator17, 0, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label59 = gtk_label_new (_("Upper Left Tensioner"));
  gtk_widget_show (label59);
  gtk_table_attach (GTK_TABLE (table17), label59, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label59), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label59), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label59), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label59), TRUE);

  label60 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label60);
  gtk_table_attach (GTK_TABLE (table17), label60, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label60), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label60), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label60), TRUE);

  label61 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label61);
  gtk_table_attach (GTK_TABLE (table17), label61, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label61), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label61), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label61), TRUE);

  ul_actual_pos_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (ul_actual_pos_guided);
  gtk_table_attach (GTK_TABLE (table17), ul_actual_pos_guided, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (ul_actual_pos_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (ul_actual_pos_guided), 2);

  ul_actual_force_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[UL_TENSIONER] * motor_limit_current_fractions_const[UL_TENSIONER], 0.1, 1, 0)));
  gtk_widget_show (ul_actual_force_guided);
  gtk_table_attach (GTK_TABLE (table17), ul_actual_force_guided, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (ul_actual_force_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (ul_actual_force_guided), 2);

  table18 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table18);
  gtk_box_pack_start (GTK_BOX (vbox2), table18, TRUE, TRUE, 0);

  hseparator18 = gtk_hseparator_new ();
  gtk_widget_show (hseparator18);
  gtk_table_attach (GTK_TABLE (table18), hseparator18, 0, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label62 = gtk_label_new (_("Upper Right Tensioner"));
  gtk_widget_show (label62);
  gtk_table_attach (GTK_TABLE (table18), label62, 0, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label62), 0, 0.5);
  gtk_misc_set_padding (GTK_MISC (label62), 3, 1);
  gtk_label_set_ellipsize (GTK_LABEL (label62), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label62), TRUE);

  label63 = gtk_label_new (_("Actual Postion (mm)"));
  gtk_widget_show (label63);
  gtk_table_attach (GTK_TABLE (table18), label63, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label63), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label63), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label63), TRUE);

  label64 = gtk_label_new (_("Actual Force (ADC Ticks)"));
  gtk_widget_show (label64);
  gtk_table_attach (GTK_TABLE (table18), label64, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_justify (GTK_LABEL (label64), GTK_JUSTIFY_CENTER);
  gtk_label_set_ellipsize (GTK_LABEL (label64), PANGO_ELLIPSIZE_END);
  gtk_label_set_single_line_mode (GTK_LABEL (label64), TRUE);

  ur_actual_pos_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -100, 400, 0.1, 1, 0)));
  gtk_widget_show (ur_actual_pos_guided);
  gtk_table_attach (GTK_TABLE (table18), ur_actual_pos_guided, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (ur_actual_pos_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (ur_actual_pos_guided), 2);

  ur_actual_force_guided = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, motor_max_force_const[UR_TENSIONER] * motor_limit_current_fractions_const[UR_TENSIONER], 0.1, 1, 0)));
  gtk_widget_show (ur_actual_force_guided);
  gtk_table_attach (GTK_TABLE (table18), ur_actual_force_guided, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_widget_set_sensitive (ur_actual_force_guided, FALSE);
  gtk_scale_set_digits (GTK_SCALE (ur_actual_force_guided), 2);

  hbox7 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox7);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox7, FALSE, FALSE, 0);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (hbox7), hbox8, TRUE, TRUE, 0);

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox8), vbox3, TRUE, TRUE, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), vbox4, TRUE, TRUE, 0);

  label70 = gtk_label_new (_("Steering"));
  gtk_widget_show (label70);
  gtk_box_pack_start (GTK_BOX (vbox4), label70, FALSE, FALSE, 0);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox9, TRUE, TRUE, 0);

  hscale20 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, -1, 1, 0.1, 0.2, 0)));
  gtk_widget_show (hscale20);
  gtk_box_pack_start (GTK_BOX (hbox9), hscale20, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (hscale20, FALSE);

  vscale1 = gtk_vscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0.2, -1, 1, 0.1, 0.2, 0)));
  gtk_widget_show (vscale1);
  gtk_box_pack_start (GTK_BOX (hbox9), vscale1, TRUE, TRUE, 0);
  gtk_widget_set_size_request (vscale1, -1, 120);
  gtk_widget_set_sensitive (vscale1, FALSE);
  gtk_range_set_inverted (GTK_RANGE (vscale1), TRUE);

  table19 = gtk_table_new (4, 2, FALSE);
  gtk_widget_show (table19);
  gtk_box_pack_start (GTK_BOX (hbox7), table19, TRUE, FALSE, 0);

  label68 = gtk_label_new (_("UNKNOWN"));
  gtk_widget_show (label68);
  gtk_table_attach (GTK_TABLE (table19), label68, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label68), 0, 0.5);

  label69 = gtk_label_new (_("7.68"));
  gtk_widget_show (label69);
  gtk_table_attach (GTK_TABLE (table19), label69, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label69), 0, 0.5);

  label65 = gtk_label_new (_("Mode: "));
  gtk_widget_show (label65);
  gtk_table_attach (GTK_TABLE (table19), label65, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label65), 0, 0.5);

  label66 = gtk_label_new (_("Separation: "));
  gtk_widget_show (label66);
  gtk_table_attach (GTK_TABLE (table19), label66, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label66), 0, 0.5);

  run_pause = gtk_label_new (_("Run/Pause: "));
  gtk_widget_show (run_pause);
  gtk_table_attach (GTK_TABLE (table19), run_pause, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (run_pause), 0, 0.5);

  pause_label = gtk_label_new (_("Paused"));
  gtk_widget_show (pause_label);
  gtk_table_attach (GTK_TABLE (table19), pause_label, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (pause_label), 0, 0.5);

  next_mode_label = gtk_label_new (_("Next Mode:"));
  gtk_widget_show (next_mode_label);
  gtk_table_attach (GTK_TABLE (table19), next_mode_label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (next_mode_label), 0, 0.5);

  next_mode = gtk_label_new (_("none"));
  gtk_widget_show (next_mode);
  gtk_table_attach (GTK_TABLE (table19), next_mode, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (next_mode), 0, 0.5);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox7), vbox5, TRUE, TRUE, 0);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox5), hbox11, TRUE, TRUE, 0);

  image6 = gtk_image_new_from_stock ("gtk-dialog-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox11), image6, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (image6, FALSE);

  image7 = gtk_image_new_from_stock ("gtk-dialog-error", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox11), image7, TRUE, TRUE, 0);
  gtk_widget_set_sensitive (image7, FALSE);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (vbox5), scrolledwindow1, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  textview1 = gtk_text_view_new ();
  gtk_widget_show (textview1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), textview1);
  gtk_widget_set_size_request (textview1, 197, 82);
  gtk_text_view_set_editable (GTK_TEXT_VIEW (textview1), FALSE);
  gtk_text_view_set_accepts_tab (GTK_TEXT_VIEW (textview1), FALSE);
  gtk_text_view_set_cursor_visible (GTK_TEXT_VIEW (textview1), FALSE);

  label37 = gtk_label_new (_("Guided Mode"));
  gtk_widget_show (label37);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook),
#ifdef USE_MANUAL_MODE  
  1
#else /* USE_MANUAL_MODE */
  0
#endif /* USE_MANUAL_MODE */
  ), label37);

  g_signal_connect ((gpointer) main_window, "delete_event",
                    G_CALLBACK (on_quit),
                    NULL);
  g_signal_connect ((gpointer) main_window, "destroy_event",
                    G_CALLBACK (gtk_main_quit),
                    NULL);
  g_signal_connect ((gpointer) main_notebook, "switch_page",
                    G_CALLBACK (on_main_notebook_change_current_page),
                    NULL);
#ifdef USE_MANUAL_MODE
  g_signal_connect ((gpointer) inner_slide_set_pos, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) inner_slide_set_pos, "button_press_event",
                    G_CALLBACK (on_inner_slide_set_pos_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) inner_slide_set_pos, "button_release_event",
                    G_CALLBACK (on_inner_slide_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) inner_slide_set_pos, "key_release_event",
                    G_CALLBACK (on_inner_slide_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) inner_slide_set_force, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) outer_slide_set_force, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) outer_slide_set_pos, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) outer_slide_set_pos, "button_press_event",
                    G_CALLBACK (on_outer_slide_set_pos_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) outer_slide_set_pos, "button_release_event",
                    G_CALLBACK (on_outer_slide_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) outer_slide_set_pos, "key_release_event",
                    G_CALLBACK (on_outer_slide_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) inner_set_pos, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) inner_set_pos, "button_press_event",
                    G_CALLBACK (on_inner_set_pos_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) inner_set_pos, "button_release_event",
                    G_CALLBACK (on_inner_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) inner_set_pos, "key_release_event",
                    G_CALLBACK (on_inner_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) inner_set_force, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) bot_set_pos, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) bot_set_pos, "button_press_event",
                    G_CALLBACK (on_bot_set_pos_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) bot_set_pos, "button_release_event",
                    G_CALLBACK (on_bot_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) bot_set_pos, "key_release_event",
                    G_CALLBACK (on_bot_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) bot_set_force, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) ul_set_pos, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) ul_set_pos, "button_press_event",
                    G_CALLBACK (on_ul_set_pos_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) ul_set_pos, "button_release_event",
                    G_CALLBACK (on_ul_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) ul_set_pos, "key_release_event",
                    G_CALLBACK (on_ul_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) ul_set_force, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) ur_set_pos, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) ur_set_pos, "button_press_event",
                    G_CALLBACK (on_ur_set_pos_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) ur_set_pos, "button_release_event",
                    G_CALLBACK (on_ur_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) ur_set_pos, "key_release_event",
                    G_CALLBACK (on_ur_set_pos_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) ur_set_force, "value_changed",
                    G_CALLBACK (manual_value_changed),
                    NULL);
  g_signal_connect ((gpointer) apply_btn, "clicked",
                    G_CALLBACK (on_apply_btn_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2, "toggled",
                    G_CALLBACK (on_checkbutton2_toggled),
                    NULL);

#endif /* USE_MANUAL_MODE */
  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, main_notebook, "main_notebook");

#ifdef USE_MANUAL_MODE
  GLADE_HOOKUP_OBJECT (main_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_window, label1, "label1");
  GLADE_HOOKUP_OBJECT (main_window, table11, "table11");
  GLADE_HOOKUP_OBJECT (main_window, inner_slide_actual_pos, "inner_slide_actual_pos");
  GLADE_HOOKUP_OBJECT (main_window, inner_slide_set_pos, "inner_slide_set_pos");
  GLADE_HOOKUP_OBJECT (main_window, inner_slide_set_force, "inner_slide_set_force");
  GLADE_HOOKUP_OBJECT (main_window, label37, "label37");
  GLADE_HOOKUP_OBJECT (main_window, label38, "label38");
  GLADE_HOOKUP_OBJECT (main_window, label39, "label39");
  GLADE_HOOKUP_OBJECT (main_window, label40, "label40");
  GLADE_HOOKUP_OBJECT (main_window, inner_slide_actual_force, "inner_slide_actual_force");
  GLADE_HOOKUP_OBJECT (main_window, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (main_window, label2, "label2");
  GLADE_HOOKUP_OBJECT (main_window, table6, "table6");
  GLADE_HOOKUP_OBJECT (main_window, outer_slide_actual_pos, "outer_slide_actual_pos");
  GLADE_HOOKUP_OBJECT (main_window, outer_slide_set_force, "outer_slide_set_force");
  GLADE_HOOKUP_OBJECT (main_window, label15, "label15");
  GLADE_HOOKUP_OBJECT (main_window, label16, "label16");
  GLADE_HOOKUP_OBJECT (main_window, label17, "label17");
  GLADE_HOOKUP_OBJECT (main_window, label18, "label18");
  GLADE_HOOKUP_OBJECT (main_window, outer_slide_actual_force, "outer_slide_actual_force");
  GLADE_HOOKUP_OBJECT (main_window, outer_slide_set_pos, "outer_slide_set_pos");
  GLADE_HOOKUP_OBJECT (main_window, hseparator7, "hseparator7");
  GLADE_HOOKUP_OBJECT (main_window, label3, "label3");
  GLADE_HOOKUP_OBJECT (main_window, table7, "table7");
  GLADE_HOOKUP_OBJECT (main_window, inner_actual_pos, "inner_actual_pos");
  GLADE_HOOKUP_OBJECT (main_window, inner_set_pos, "inner_set_pos");
  GLADE_HOOKUP_OBJECT (main_window, inner_set_force, "inner_set_force");
  GLADE_HOOKUP_OBJECT (main_window, label19, "label19");
  GLADE_HOOKUP_OBJECT (main_window, label20, "label20");
  GLADE_HOOKUP_OBJECT (main_window, label21, "label21");
  GLADE_HOOKUP_OBJECT (main_window, label22, "label22");
  GLADE_HOOKUP_OBJECT (main_window, inner_actual_force, "inner_actual_force");
  GLADE_HOOKUP_OBJECT (main_window, hseparator8, "hseparator8");
  GLADE_HOOKUP_OBJECT (main_window, label4, "label4");
  GLADE_HOOKUP_OBJECT (main_window, table8, "table8");
  GLADE_HOOKUP_OBJECT (main_window, bot_actual_pos, "bot_actual_pos");
  GLADE_HOOKUP_OBJECT (main_window, bot_set_pos, "bot_set_pos");
  GLADE_HOOKUP_OBJECT (main_window, bot_set_force, "bot_set_force");
  GLADE_HOOKUP_OBJECT (main_window, label23, "label23");
  GLADE_HOOKUP_OBJECT (main_window, label24, "label24");
  GLADE_HOOKUP_OBJECT (main_window, label25, "label25");
  GLADE_HOOKUP_OBJECT (main_window, label26, "label26");
  GLADE_HOOKUP_OBJECT (main_window, bot_actual_force, "bot_actual_force");
  GLADE_HOOKUP_OBJECT (main_window, hseparator9, "hseparator9");
  GLADE_HOOKUP_OBJECT (main_window, label5, "label5");
  GLADE_HOOKUP_OBJECT (main_window, table9, "table9");
  GLADE_HOOKUP_OBJECT (main_window, ul_actual_pos, "ul_actual_pos");
  GLADE_HOOKUP_OBJECT (main_window, ul_set_pos, "ul_set_pos");
  GLADE_HOOKUP_OBJECT (main_window, ul_set_force, "ul_set_force");
  GLADE_HOOKUP_OBJECT (main_window, label27, "label27");
  GLADE_HOOKUP_OBJECT (main_window, label28, "label28");
  GLADE_HOOKUP_OBJECT (main_window, label29, "label29");
  GLADE_HOOKUP_OBJECT (main_window, label30, "label30");
  GLADE_HOOKUP_OBJECT (main_window, ul_actual_force, "ul_actual_force");
  GLADE_HOOKUP_OBJECT (main_window, hseparator10, "hseparator10");
  GLADE_HOOKUP_OBJECT (main_window, label6, "label6");
  GLADE_HOOKUP_OBJECT (main_window, table10, "table10");
  GLADE_HOOKUP_OBJECT (main_window, ur_actual_pos, "ur_actual_pos");
  GLADE_HOOKUP_OBJECT (main_window, ur_set_pos, "ur_set_pos");
  GLADE_HOOKUP_OBJECT (main_window, ur_set_force, "ur_set_force");
  GLADE_HOOKUP_OBJECT (main_window, label31, "label31");
  GLADE_HOOKUP_OBJECT (main_window, label32, "label32");
  GLADE_HOOKUP_OBJECT (main_window, label33, "label33");
  GLADE_HOOKUP_OBJECT (main_window, label34, "label34");
  GLADE_HOOKUP_OBJECT (main_window, ur_actual_force, "ur_actual_force");
  GLADE_HOOKUP_OBJECT (main_window, hseparator11, "hseparator11");
  GLADE_HOOKUP_OBJECT (main_window, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (main_window, apply_btn, "apply_btn");
  GLADE_HOOKUP_OBJECT (main_window, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (main_window, image2, "image2");
  GLADE_HOOKUP_OBJECT (main_window, label36, "label36");
  GLADE_HOOKUP_OBJECT (main_window, checkbutton1, "checkbutton1");
  GLADE_HOOKUP_OBJECT (main_window, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (main_window, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (main_window, image3, "image3");
  GLADE_HOOKUP_OBJECT (main_window, label41, "label41");
  GLADE_HOOKUP_OBJECT (main_window, checkbutton2, "checkbutton2");
  GLADE_HOOKUP_OBJECT (main_window, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (main_window, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (main_window, image5, "image5");
  GLADE_HOOKUP_OBJECT (main_window, label71, "label71");
  GLADE_HOOKUP_OBJECT (main_window, statusbar1, "statusbar1");
  GLADE_HOOKUP_OBJECT (main_window, label_manual_mode, "label_manual_mode");
#endif /* USE_MANUAL_MODE */

  GLADE_HOOKUP_OBJECT (main_window, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (main_window, table12, "table12");
  GLADE_HOOKUP_OBJECT (main_window, hseparator12, "hseparator12");
  GLADE_HOOKUP_OBJECT (main_window, label44, "label44");
  GLADE_HOOKUP_OBJECT (main_window, label45, "label45");
  GLADE_HOOKUP_OBJECT (main_window, label46, "label46");
  GLADE_HOOKUP_OBJECT (main_window, inner_slide_actual_pos_guided, "inner_slide_actual_pos_guided");
  GLADE_HOOKUP_OBJECT (main_window, inner_slide_actual_force_guided, "inner_slide_actual_force_guided");
  GLADE_HOOKUP_OBJECT (main_window, table14, "table14");
  GLADE_HOOKUP_OBJECT (main_window, hseparator14, "hseparator14");
  GLADE_HOOKUP_OBJECT (main_window, label50, "label50");
  GLADE_HOOKUP_OBJECT (main_window, label51, "label51");
  GLADE_HOOKUP_OBJECT (main_window, label52, "label52");
  GLADE_HOOKUP_OBJECT (main_window, outer_slide_actual_pos_guided, "outer_slide_actual_pos_guided");
  GLADE_HOOKUP_OBJECT (main_window, outer_slide_actual_force_guided, "outer_slide_actual_force_guided");
  GLADE_HOOKUP_OBJECT (main_window, table15, "table15");
  GLADE_HOOKUP_OBJECT (main_window, hseparator15, "hseparator15");
  GLADE_HOOKUP_OBJECT (main_window, label53, "label53");
  GLADE_HOOKUP_OBJECT (main_window, label54, "label54");
  GLADE_HOOKUP_OBJECT (main_window, label55, "label55");
  GLADE_HOOKUP_OBJECT (main_window, inner_actual_pos_guided, "inner_actual_pos_guided");
  GLADE_HOOKUP_OBJECT (main_window, inner_actual_force_guided, "inner_actual_force_guided");
  GLADE_HOOKUP_OBJECT (main_window, table16, "table16");
  GLADE_HOOKUP_OBJECT (main_window, hseparator16, "hseparator16");
  GLADE_HOOKUP_OBJECT (main_window, label56, "label56");
  GLADE_HOOKUP_OBJECT (main_window, label57, "label57");
  GLADE_HOOKUP_OBJECT (main_window, label58, "label58");
  GLADE_HOOKUP_OBJECT (main_window, bot_actual_pos_guided, "bot_actual_pos_guided");
  GLADE_HOOKUP_OBJECT (main_window, bot_actual_force_guided, "bot_actual_force_guided");
  GLADE_HOOKUP_OBJECT (main_window, table17, "table17");
  GLADE_HOOKUP_OBJECT (main_window, hseparator17, "hseparator17");
  GLADE_HOOKUP_OBJECT (main_window, label59, "label59");
  GLADE_HOOKUP_OBJECT (main_window, label60, "label60");
  GLADE_HOOKUP_OBJECT (main_window, label61, "label61");
  GLADE_HOOKUP_OBJECT (main_window, ul_actual_pos_guided, "ul_actual_pos_guided");
  GLADE_HOOKUP_OBJECT (main_window, ul_actual_force_guided, "ul_actual_force_guided");
  GLADE_HOOKUP_OBJECT (main_window, table18, "table18");
  GLADE_HOOKUP_OBJECT (main_window, hseparator18, "hseparator18");
  GLADE_HOOKUP_OBJECT (main_window, label62, "label62");
  GLADE_HOOKUP_OBJECT (main_window, label63, "label63");
  GLADE_HOOKUP_OBJECT (main_window, label64, "label64");
  GLADE_HOOKUP_OBJECT (main_window, ur_actual_pos_guided, "ur_actual_pos_guided");
  GLADE_HOOKUP_OBJECT (main_window, ur_actual_force_guided, "ur_actual_force_guided");
  GLADE_HOOKUP_OBJECT (main_window, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (main_window, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (main_window, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (main_window, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (main_window, label70, "label70");
  GLADE_HOOKUP_OBJECT (main_window, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (main_window, hscale20, "hscale20");
  GLADE_HOOKUP_OBJECT (main_window, vscale1, "vscale1");
  GLADE_HOOKUP_OBJECT (main_window, table19, "table19");
  GLADE_HOOKUP_OBJECT (main_window, label68, "label68");
  GLADE_HOOKUP_OBJECT (main_window, label69, "label69");
  GLADE_HOOKUP_OBJECT (main_window, label65, "label65");
  GLADE_HOOKUP_OBJECT (main_window, label66, "label66");
  GLADE_HOOKUP_OBJECT (main_window, run_pause, "run_pause");
  GLADE_HOOKUP_OBJECT (main_window, pause_label, "pause_label");
  GLADE_HOOKUP_OBJECT (main_window, next_mode_label, "next_mode_label");
  GLADE_HOOKUP_OBJECT (main_window, next_mode, "next_mode");
  GLADE_HOOKUP_OBJECT (main_window, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (main_window, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (main_window, image6, "image6");
  GLADE_HOOKUP_OBJECT (main_window, image7, "image7");
  GLADE_HOOKUP_OBJECT (main_window, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (main_window, textview1, "textview1");
  GLADE_HOOKUP_OBJECT (main_window, label37, "label37");
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, tooltips, "tooltips");

#ifdef USE_MANUAL_MODE
  gtk_widget_grab_default (apply_btn);
#endif /* USE_MANUAL_MODE */
  return main_window;
}

GtkWidget*
create_menu1 (void)
{
  GtkWidget *menu1;
  GtkWidget *rezero1;
  GtkWidget *image4;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  menu1 = gtk_menu_new ();

  rezero1 = gtk_image_menu_item_new_with_mnemonic (_("Rezero"));
  gtk_widget_show (rezero1);
  gtk_container_add (GTK_CONTAINER (menu1), rezero1);
  gtk_tooltips_set_tip (tooltips, rezero1, _("Set the current motor position to zero."), NULL);

  image4 = gtk_image_new_from_stock ("gtk-revert-to-saved", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image4);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (rezero1), image4);

  g_signal_connect ((gpointer) rezero1, "activate",
                    G_CALLBACK (on_rezero1_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menu1, menu1, "menu1");
  GLADE_HOOKUP_OBJECT (menu1, rezero1, "rezero1");
  GLADE_HOOKUP_OBJECT (menu1, image4, "image4");
  GLADE_HOOKUP_OBJECT_NO_REF (menu1, tooltips, "tooltips");

  return menu1;
}


