/**	@file gui_main.c
 *	@brief Main file for all gui stuff. Originally generated by Glade.
 *
 *	@author Cornell Wright
 */

#include "gui_config.h"

#include <gtk/gtk.h>

#include "gui_interface.h"
#include "gui_support.h"

#ifdef G_OS_WIN32
gchar *package_prefix = "//"; //PACKAGE_PREFIX;
gchar *package_data_dir = "//"; //PACKAGE_DATA_DIR;
gchar *package_locale_dir = "//"; //PACKAGE_LOCALE_DIR;
#endif

// Pointer to the main window
GtkWidget *main_window;
GtkWidget *menu1;

/** @brief initializes the gui
 *
 *	@param argc Number of command line arguments
 *	@param argv Pointer to the arguments
 *	@param main_loop function pointer to the main loop.
 */
int
gui_init (int argc, char *argv[], int (*main_loop)(void *))
{

  gchar *pixmap_dir;
#ifdef G_OS_WIN32
  package_prefix = g_win32_get_package_installation_directory (NULL, NULL);
  package_data_dir = g_build_filename (package_prefix, "share", NULL);
  package_locale_dir =
    g_build_filename (package_prefix, "share", "locale", NULL);
#endif

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, package_locale_dir);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  // Initialize GTK
  gtk_init (&argc, &argv);

  pixmap_dir = g_build_filename (package_data_dir, PACKAGE, "pixmaps", NULL);
  add_pixmap_directory (pixmap_dir);
  g_free (pixmap_dir);


  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  main_window = create_main_window ();
  menu1 = create_menu1();
  gtk_widget_show (main_window);
  g_signal_connect ((gpointer) main_window, "destroy",
		    G_CALLBACK (gtk_main_quit), NULL);

  // Add the timeout so that our main loop can do stuff.
  //g_timeout_add(25, main_loop, NULL);
  //g_timeout_add(50, main_loop, NULL);
  //g_idle_add(main_loop, NULL);

  // Maximize the main window
  gtk_window_maximize(GTK_WINDOW(main_window));

  //gtk_main ();
  // Run the main loop until it doesn't want to be run anymore
  //while ( main_loop(NULL) ) ;

  return 0;
}


int gui_quit(void)
{

  // If we get here we're quitting.

#ifdef G_OS_WIN32
  g_free (package_prefix);
  g_free (package_data_dir);
  g_free (package_locale_dir);
#endif

  return 0;
}

